In [13]:
from numpy import genfromtxt

product_data = genfromtxt('/kaggle/input/demodatacsv/demodata.csv', delimiter='\t')

print(product_data)

import numpy as np

sample_array = np.asarray([ [1,2,3], [4,5,6], [7,8,9] ])

np.savetxt("my_first_demo.csv", sample_array, delimiter=",")

import pandas as pd

sample_df=pd.read_csv('/kaggle/input/demodatacsv/demodata.csv', sep='\t' , header=None)

sample_df.head()

sample_df.to_csv('demo_sample_df.csv')

#Student name: Khalid Nimri
#Student ID: 2140145


[[14. 32. 33.]
 [24. 45. 26.]
 [27. 38. 39.]]
